### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by Cirlias** [KunoichiZ/3OT-NTR-Plugin#1]
Hey

Everytime i start up the 3OT NTR plugin download and press A to install it says 'updating plugin to the last version... Download Failed!'
My system version is 11.6 and the 3OT Is a CIA installed game

Somebody can help ? Thansk in advance

**Comment by KunoichiZ** [comment]
Because of Github's changes, the app now longer works. Download it manually. And it doesn't work with the update to the game nor the DLC. Don't bother.
